### PR TITLE
Git task 2 completed

### PR DESCRIPTION
**Pull request by chinmaya-sahoo**

### CODE REVIEW

**Comment by ritpa2005** [comment]
Don't create a new file in Task 2 folder, just update your file in Task 1 folder.

**Comment by chinmaya-sahoo** [comment]
OK sir...but I have also updated my file in taks-1...

**Comment by ritpa2005** [comment]
Then delete the file in Task 2 folder, and commit.

**Comment by chinmaya-sahoo** [comment]
Ok done sir, Please check

**Comment by ritpa2005** [comment]
Yes. Good work.

**Pull request merged**
