### PR TITLE
Web Task Completed

### PR DESCRIPTION
**Pull request by 123Dibya**
https://portfolio-dips.netlify.app/

### CODE REVIEW

**Comment by Khitishgithub** [comment]
Your Hosted link is not working . Fix it

**Comment by 123Dibya** [comment]
> Your Hosted link is not working . Fix it 

Bhaiya mere laptop Mai toh chal raha haai

**Comment by 123Dibya** [comment]
> Your Hosted link is not working . Fix it 

Bhaiya fix ho gaya

**Comment by 123Dibya** [comment]
> Your Hosted link is not working . Fix it 

Bhaiya I have fixed it.

**Comment by Khitishgithub** [comment]
Your page is not responsive for smaller screen devices . make it responsive .

**Comment by 123Dibya** [comment]
> Your page is not responsive for smaller screen devices . make it responsive .

Responsive for smaller screen is done, you can check it.

**Pull request merged**
