### PR TITLE
task 3 completed

### PR DESCRIPTION
**Pull request by bprava**

### CODE REVIEW

**Comment by Khitishgithub** [comment]
Add your hosted link in a txt file

**Comment by Khitishgithub** [comment]
Screenshot 2024-03-29 234357
In smaller screen devices your image is overlapping your text .

Screenshot 2024-03-29 234609
You should remove the position : absolute from img src tag to prevent the overlapping in the smaller screen devices . In gallery section you should keep all image's height and width should be same  by defining px in css .

**Comment by bprava** [comment]
Bhaiya ye Mein size Kam karne ke baad bhi nnahi ho raha he

**Comment by Khitishgithub** [comment]
Screenshot 2024-03-29 235603
first of all your body should be end at the last of the code . but in your code it ended after image tag . fix it .  tag is used to embeded an image in a html page . Don't use <image> tag .

**Pull request merged**
