### PR TITLE
web dev task completed

### PR DESCRIPTION
**Pull request by SouravSiku**

### CODE REVIEW

**Comment by Khitishgithub** [comment]
Please add your hosted link .Whatever Link you provided us is your local host link . https://youtu.be/OltY8JIaP-4?si=TUxXv4i4330Yi4oJ watch this video to learn how a webpage is hosted .

**Comment by SouravSiku** [comment]
https://souravsiku.github.io/WevDevTask-SouravDash.github.io/

**Comment by Khitishgithub** [comment]
Screenshot 2024-04-01 140348
your image is not appearing in your webpage . fix it 


Screenshot 2024-04-01 140458
you should remove image/ from the img src tag and rest part is as it is . After that rehost the page . Then your image will appears .

**Comment by SouravSiku** [comment]
https://souravsiku.github.io/WevDevTask-SouravDash.github.io/

**Pull request merged**
