### PR TITLE
git web dev task completed

### PR DESCRIPTION
**Pull request by BarsaKujur**
https://barsakujur.github.io/web-development/

### CODE REVIEW

**Comment by Khitishgithub** [comment]
Your link is not working . Fix it

**Comment by BarsaKujur** [comment]
> Your link is not working . Fix it

done

**Comment by Khitishgithub** [comment]
Your page is looking very nice . but don't use your portfolio profile image as  your background image . This  will create a responsive issue in smaller screen devices  .  You should place the image  by using CSS  flex .

**Comment by BarsaKujur** [comment]
changes done

**Comment by Khitishgithub** [comment]
Screenshot 2024-03-26 215340
In desktop view the image is overlapping the project section

**Pull request merged**
